collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.734767
color:
  saturation: 0.1200717
  brandStrength: 0.3335775074083358
  lightness: 0.1129032
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  rhythmicContrast: 0.7598566
layout_spectrum: 0.05017921
name: Man Sized Steaks and Chops
