collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6003584
  brandStrength: 0.3335775074083358
  lightness: 1
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  rhythmicContrast: 0.5250896
typography_spectrum: 0.7096774
layout_spectrum: 0.05017921
name: Man Sized Steaks and Chops
